Turkish language support added
DevilXD/TwitchDropsMiner pull request #119
Opened 2023-01-17 11:55 UTC by alikdb

2023-01-17 13:42 UTC, DevilXD commented
Looks good 👍 Could you also add yourself a credit to the README file? If not, I can do that after the merge instead, if needed.

2023-01-17 21:46 UTC, alikdb commented
i think okay 😆

2023-01-18 06:11 UTC, DevilXD reviewed
As the markdown comment said right above the credits section, you've either didn't add two spaces on the end of the previous line, or you've did, and your text/code editor trimmed them after saving the file. They're required there for proper formatting on Github, without them both lines will collapse into one.

2023-01-18 06:11 UTC, DevilXD commented on README.md
>  @zarigata - For the entirety of the Portuguese (Português) translation.
```suggestion
@zarigata - For the entirety of the Portuguese (Português) translation.  
```

2023-01-18 06:44 UTC, alikdb commented
Is ready?

2023-01-18 14:46 UTC, DevilXD requested changes
No, you've messed up the formatting of these two lines for no apparent reason in the process of adding your last two commits. You could've just applied my suggestion straight from Github instead of pushing your own separate commit and it'd be good, now you have to either apply those two or "do it properly" in your own commit now.

2023-01-18 14:46 UTC, DevilXD commented on README.md
> +https://www.buymeacoffee.com/DevilXD
```suggestion
    https://www.buymeacoffee.com/DevilXD
```

2023-01-18 14:46 UTC, DevilXD commented on README.md
> +https://www.patreon.com/bePatron?u=26937862
```suggestion
    https://www.patreon.com/bePatron?u=26937862
```

2023-01-19 06:13 UTC, DevilXD commented on README.md
> +https://www.patreon.com/bePatron?u=26937862
@alikdb This one also needs to be accepted.

2023-01-19 15:42 UTC, DevilXD approved these changes
Perfect! Thank you for your contribution :)

2023-01-19 15:43 UTC, merged