Added Ukrainian translation
DevilXD/TwitchDropsMiner pull request #230
Opened 2023-06-16 18:03 UTC by DevilXD

@Nollasko I've created a PR for you. Please verify everything's correct and in place, and let me know once you do so.

2023-06-16 19:21 UTC, Nollasko requested changes

2023-06-16 19:21 UTC, Nollasko commented on lang/Українська.json
> +    "twofa_code_required": "Потрібен жетоне двухфакторної аутентифікації."
"twofa_code_required": "Потрібен жетон двухфакторної аутентифікації."

2023-06-16 19:21 UTC, Nollasko commented on lang/Українська.json
> +      "adding_campaigns": "Додавання компаній до інвентарю... {counter}"
"adding_campaigns": "Додавання кампаній до інвентарю... {counter}"

2023-06-16 19:21 UTC, Nollasko commented on lang/Українська.json
> +        "linked": "Ззв'язані",
"linked": "Зв'язані",

2023-06-16 19:21 UTC, Nollasko commented on lang/Українська.json
> +      "reload_text": "Більшість змін потребують перезавантаження, щоб набути негайного заподії: "
"reload_text": "Більшість змін потребують перезавантаження, щоб набути негайної дії: "

2023-06-16 19:38 UTC, Nollasko requested changes
Sorry, made few mistakes

2023-06-16 19:38 UTC, Nollasko commented on lang/Українська.json
> +    "incorrect_twofa_code": "Неправильний код двухфакторної аутентифікації.",
"incorrect_twofa_code": "Неправильний код двофакторної аутентифікації.",

2023-06-16 19:38 UTC, Nollasko commented on lang/Українська.json
> +        "expired": "Просрочені",
"expired": "Прострочені",

2023-06-17 15:54 UTC, DevilXD commented
Please review the new changes, and let me know what you think.

If you'd like to test the built application from this PR, you can download the Windows build from the CI artifacts, at the bottom of the page here: https://github.com/DevilXD/TwitchDropsMiner/actions/runs/5298922029?pr=230

2023-06-17 17:52 UTC, Nollasko requested changes
There are strings that can't be translated due to their absence in .json file
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/dce7750e-38d2-4ea0-ba07-6864c36a2d32)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/20dd8868-ff5c-435d-88a6-4259aefaddbc)
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/b9250be9-1df0-4635-87a0-ded588710c1b)

2023-06-17 17:52 UTC, Nollasko commented on lang/Українська.json
>          "active": "Діюче \u2714",
"active": "Діюча \u2714",

2023-06-17 17:56 UTC, Nollasko requested changes
I hope this is the last review, please forgive me for my inattention

2023-06-17 17:56 UTC, Nollasko commented on lang/Українська.json
> +      "name": "Прогрес кампанії",
"name": "Поступ кампанії",

2023-06-17 17:56 UTC, Nollasko commented on lang/Українська.json
> +      "drop_progress": "Прогрес:",
"drop_progress": "Поступ:",

2023-06-17 17:56 UTC, Nollasko commented on lang/Українська.json
> +      "campaign_progress": "Прогрес:"
"campaign_progress": "Поступ:"

2023-06-17 19:33 UTC, DevilXD commented
> There are strings that can't be translated due to their absence in .json file

That's intentional. The About section is my own personal section, written with my own words. Translating it would be like "putting words I never said into my mouth", which is why there's no need nor way to translate those, and it should stay like that.

The "Language" option is untranslatable to allow people to find the language option and change it, even if they'd switch to a language they don't otherwise speak. Some apps translate the language change option too, and once the language switches, the user would be then unable to find the language change option again and change back otherwise.

The Twitch code message that's printed into the chat is meant to be translated at some point in the future - I haven't gotten around to making a translation key for it yet. For now, it can't be translated.

***

I've pushed out more changes as requested. Is it good now?

2023-06-17 20:14 UTC, Nollasko commented
@DevilXD found one more untranslatable string.
![image](https://github.com/DevilXD/TwitchDropsMiner/assets/67293930/44348eea-080c-4039-94c4-419c17a600cf)

Everything else seems right, u can close this.

2023-06-17 20:36 UTC, DevilXD commented
> found one more untranslatable string.

It's from an unfinished, in-progress feature that I haven't ended implementing properly yet. Again, translation to-be-added later. The dev version is not stable for a reason, nothing is guaranteed to work as it should.

> Everything else seems right

Merging then. Thank you for your contribution 🙂

2023-06-17 20:36 UTC, merged