Created Italian translation
DevilXD/TwitchDropsMiner pull request #240
Opened 2023-06-26 19:41 UTC by casungo

2023-06-27 18:57 UTC, DevilXD requested changes
Hello o/

Overall, it looks okay. Please add a credit line to the README file as a part of this PR too, if possible.

2023-06-27 18:57 UTC, DevilXD commented on lang/Italiano.json
> +}
```suggestion
}

```

2023-06-27 18:57 UTC, DevilXD commented on lang/Italiano.json
> +}
The file has to end with a single, empty new line, per the suggestion.

2023-06-27 22:30 UTC, casungo commented
Sure, commit coming right up :)

2023-06-28 18:23 UTC, DevilXD commented
Perfect! Thank you for the contribution 🙂

2023-06-28 18:24 UTC, merged